[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "97rfnZNfv2rgxUp8qE2wXtUp8mEJ2fpz1sXgDS4y611R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
